"""Add created_by_id to GroceryStore

Revision ID: 2555f023661d
Revises: 
Create Date: 2025-05-10 11:42:49.466116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2555f023661d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('PRODUCE', 'DELI', 'BAKERY', 'PANTRY', 'FROZEN', 'REFRIGERATED', 'COSMETICS', 'PERSONAL_CARE', 'HOUSEHOLD', 'PET_SUPPLIES', 'CLOTHING', 'ELECTRONICS', 'TOYS', 'BOOKS', 'SPORTS', 'AUTOMOTIVE', 'BEAUTY', 'HEALTH', 'OFFICE', 'GARDEN', 'HOME_IMPROVEMENT', 'FURNITURE', 'JEWELRY', 'LUGGAGE', 'Fruit', 'OTHER', name='itemcategory'),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_grocery_item_created_by_id', 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('grocery_store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_grocery_store_created_by_id', 'user', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery_store', schema=None) as batch_op:
        batch_op.drop_constraint('fk_grocery_store_created_by_id', type_='foreignkey')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('grocery_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_grocery_item_created_by_id', type_='foreignkey')
        batch_op.alter_column('category',
               existing_type=sa.Enum('PRODUCE', 'DELI', 'BAKERY', 'PANTRY', 'FROZEN', 'REFRIGERATED', 'COSMETICS', 'PERSONAL_CARE', 'HOUSEHOLD', 'PET_SUPPLIES', 'CLOTHING', 'ELECTRONICS', 'TOYS', 'BOOKS', 'SPORTS', 'AUTOMOTIVE', 'BEAUTY', 'HEALTH', 'OFFICE', 'GARDEN', 'HOME_IMPROVEMENT', 'FURNITURE', 'JEWELRY', 'LUGGAGE', 'Fruit', 'OTHER', name='itemcategory'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
